spring:
  main:
    web-application-type: none
  application:
    name: data-integration-batch
  batch:

    job:
      enabled: true

file:
  input-file: ${DATA_INTEGRATION_BATCH_INPUT_FILE}

service:
  token-path: ${KEYCLOAK_TOKEN_PATH}
  data-integration:
    host: ${DATA_INTEGRATION_API_HOST}
    client-id: ${DATA_INTEGRATION_API_CLIENT_ID}
    client-secret: ${DATA_INTEGRATION_API_CLIENT_SECRET}
